import crypto from "node:crypto";
import { execFile } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { promisify } from "node:util";
import { app } from "electron";
import { YTMUSIC_TOOLS_DIR, YTMUSIC_DIR, ensureAppDataDirs } from "./paths";
import { log } from "./logger";
import {
  serializeYtMusicSessionCookie,
  type YtMusicSessionCookie,
} from "./ytmusicCookie";

// ---------------------------------------------------------------------------
// Binary URLs
// ---------------------------------------------------------------------------

const BINARY_URLS: Record<string, string> = {
  win32: "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe",
  darwin:
    "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos",
  linux:
    "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux",
};

// ---------------------------------------------------------------------------
// Path resolution
// ---------------------------------------------------------------------------

function getBinaryName(): string {
  return process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp";
}

/**
 * Resolve the path to the yt-dlp binary.
 * In packaged builds, checks `extraResources/bin/` first.
 * In development, falls back to the YTMUSIC_TOOLS_DIR (which gets auto-downloaded).
 */
export function getYtDlpPath(): string {
  if (app.isPackaged) {
    const resourcesPath = path.join(
      process.resourcesPath,
      "bin",
      getBinaryName(),
    );
    if (fs.existsSync(resourcesPath)) return resourcesPath;
  }
  return path.join(YTMUSIC_TOOLS_DIR, getBinaryName());
}

// ---------------------------------------------------------------------------
// Binary download / verification
// ---------------------------------------------------------------------------

/**
 * Ensure the yt-dlp binary is available.
 * - In packaged builds: expects it at the `extraResources` path.
 * - In development: downloads it on first launch.
 */
export async function ensureYtDlpBinary(): Promise<string> {
  const binaryPath = getYtDlpPath();

  try {
    await fs.promises.access(binaryPath, fs.constants.X_OK);
    return binaryPath;
  } catch {
    // Not accessible yet — proceed to download if allowed
  }

  if (app.isPackaged) {
    throw new Error(
      `yt-dlp binary not found at ${binaryPath}. Reinstall the app or place yt-dlp manually.`,
    );
  }

  const url = BINARY_URLS[process.platform];
  if (!url) {
    throw new Error(`Unsupported platform: ${process.platform}`);
  }

  log("ytdlp", "info", "Downloading yt-dlp binary", { url });

  ensureAppDataDirs();

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download yt-dlp: HTTP ${response.status}`);
  }

  const buffer = Buffer.from(await response.arrayBuffer());
  fs.writeFileSync(binaryPath, buffer);

  if (process.platform !== "win32") {
    fs.chmodSync(binaryPath, 0o755);
  }

  log("ytdlp", "info", "yt-dlp downloaded", {
    path: binaryPath,
    size: buffer.length,
  });

  return binaryPath;
}

// ---------------------------------------------------------------------------
// Cookie file writer (Netscape format)
// ---------------------------------------------------------------------------

const execFileAsync = promisify(execFile);

/**
 * Write the YT Music session cookie string to a Netscape-format cookie file
 * that yt-dlp's `--cookies` option understands.
 *
 * Each invocation writes to a unique file so concurrent yt-dlp processes
 * never read a half-written cookie file. Callers must delete the returned
 * file when done.
 *
 * @returns The path to the cookie file, or `null` if no cookie was provided.
 */
const YTDLP_COOKIE_WHITELIST = [
  "SAPISID",
  "__Secure-3PAPISID",
  "__Secure-1PAPISID",
  "APISID",
  "SSID",
];

function writeCookiesFile(
  cookie: YtMusicSessionCookie | undefined,
): string | null {
  if (!cookie) return null;
  const cookieString = serializeYtMusicSessionCookie(cookie);

  ensureAppDataDirs();

  const cookieFile = path.join(
    YTMUSIC_DIR,
    `yt-dlp-cookies-${crypto.randomUUID()}.txt`,
  );

  const lines: string[] = [
    "# Netscape HTTP Cookie File",
    "# Generated by Muxics for yt-dlp",
    "",
  ];

  const pairs = cookieString
    .split(";")
    .map((p) => p.trim())
    .filter(Boolean);

  for (const pair of pairs) {
    const eqIdx = pair.indexOf("=");
    if (eqIdx <= 0) continue;
    const name = pair.substring(0, eqIdx).trim();
    const value = pair.substring(eqIdx + 1).trim();
    if (!name) continue;

    // Only write whitelisted cookies to prevent invalid session states from breaking yt-dlp
    if (!YTDLP_COOKIE_WHITELIST.includes(name)) {
      continue;
    }

    const isSecure = name.startsWith("__Secure-");
    const secureFlag = isSecure ? "TRUE" : "FALSE";
    lines.push(`.youtube.com\tTRUE\t/\t${secureFlag}\t0\t${name}\t${value}`);
  }

  fs.writeFileSync(cookieFile, lines.join("\n"), "utf-8");
  if (process.platform !== "win32") {
    fs.chmodSync(cookieFile, 0o600);
  }
  return cookieFile;
}

// ---------------------------------------------------------------------------
// Stream URL extraction
// ---------------------------------------------------------------------------

export interface YtDlpStreamResult {
  url: string;
  loudnessDb?: number;
}

/**
 * Get a playable audio stream URL for a YouTube Music video via yt-dlp.
 *
 * yt-dlp handles:
 * - PoT token generation (BotGuard)
 * - Client version rotation (YouTube's moving target)
 * - Signature cipher / deciphering
 * - Format negotiation (opus > m4a > webm)
 * - Cookie-based auth
 *
 * @param videoId  The YouTube video ID (e.g. "dQw4w9WgXcQ")
 * @param cookieString  Optional YT Music session cookie string for auth
 * @returns The direct stream URL with all auth parameters, or null on failure.
 */
export async function getYtDlpStreamUrl(
  videoId: string,
  cookie?: YtMusicSessionCookie,
): Promise<YtDlpStreamResult | null> {
  const binaryPath = await ensureYtDlpBinary();
  const url = `https://music.youtube.com/watch?v=${videoId}`;

  const cookiesPath = writeCookiesFile(cookie);

  const args: string[] = [
    "--no-warnings",
    "-q",
    "-f",
    "ba[acodec=opus]/ba/bestaudio",
    "-g",
  ];

  if (cookiesPath) {
    args.push("--cookies", cookiesPath);
  }

  args.push(url);

  log("ytdlp", "info", "Getting stream URL", { videoId });

  try {
    const { stdout } = await execFileAsync(binaryPath, args, {
      timeout: 30_000,
      maxBuffer: 1024 * 1024,
    });

    const streamUrl = (stdout ?? "").toString().trim();
    if (!streamUrl) {
      log("ytdlp", "warn", "yt-dlp returned empty URL", { videoId });
      return null;
    }

    log("ytdlp", "info", "Stream URL obtained", {
      videoId,
      urlLength: streamUrl.length,
    });

    return { url: streamUrl };
  } catch (error) {
    const err = error as NodeJS.ErrnoException & {
      stdout?: string | Buffer;
      stderr?: string | Buffer;
    };
    const stderrStr = (err.stderr ?? "").toString().trim();
    log("ytdlp", "warn", "yt-dlp failed to get stream URL", {
      videoId,
      error: err.message,
      stderr: stderrStr.slice(0, 500),
    });
    return null;
  } finally {
    if (cookiesPath) {
      fs.rmSync(cookiesPath, { force: true });
    }
  }
}

/**
 * Get the duration (in seconds) of a YouTube Music video via yt-dlp.
 *
 * Uses `--print duration` which is much faster than a full stream URL
 * resolution because it only parses the page metadata.
 *
 * @param videoId  The YouTube video ID (e.g. "dQw4w9WgXcQ")
 * @param cookieString  Optional YT Music session cookie string for auth
 * @returns The duration in seconds, or null on failure.
 */
export async function getYtDlpDuration(
  videoId: string,
  cookie?: YtMusicSessionCookie,
): Promise<number | null> {
  const binaryPath = await ensureYtDlpBinary();
  const url = `https://music.youtube.com/watch?v=${videoId}`;
  const cookiesPath = writeCookiesFile(cookie);

  const args: string[] = ["--no-warnings", "-q", "--print", "duration"];

  if (cookiesPath) {
    args.push("--cookies", cookiesPath);
  }

  args.push(url);

  log("ytdlp", "info", "Getting track duration", { videoId });

  try {
    const { stdout } = await execFileAsync(binaryPath, args, {
      timeout: 15_000,
      maxBuffer: 1024,
    });

    const durationStr = (stdout ?? "").toString().trim();
    const duration = Number(durationStr);
    if (!Number.isFinite(duration) || duration <= 0) {
      log("ytdlp", "warn", "yt-dlp returned invalid duration", {
        videoId,
        raw: durationStr,
      });
      return null;
    }

    log("ytdlp", "info", "Track duration obtained", {
      videoId,
      duration,
    });

    return duration;
  } catch (error) {
    const err = error as NodeJS.ErrnoException & {
      stdout?: string | Buffer;
      stderr?: string | Buffer;
    };
    const stderrStr = (err.stderr ?? "").toString().trim();
    log("ytdlp", "warn", "yt-dlp failed to get duration", {
      videoId,
      error: err.message,
      stderr: stderrStr.slice(0, 500),
    });
    return null;
  } finally {
    if (cookiesPath) {
      fs.rmSync(cookiesPath, { force: true });
    }
  }
}

/**
 * Check whether the yt-dlp binary is available (exists and executable).
 * Does not attempt to download if missing.
 */
export function isYtDlpAvailable(): boolean {
  try {
    fs.accessSync(getYtDlpPath(), fs.constants.X_OK);
    return true;
  } catch {
    return false;
  }
}
